version: '3'
services:
    database:
        image: postgres:13.0-alpine
        environment:
            POSTGRES_PASSWORD: bauth
            POSTGRES_USER: bauth
            POSTGRES_DB: bauth
        ports:
            - 5432:5432
        volumes:
            - .docker-data/postgresql:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - database
