version: '3'
services:
    database:
        image: postgres:12.4-alpine
        environment:
            POSTGRES_PASSWORD: auth
            POSTGRES_USER: auth
            POSTGRES_DB: auth
        ports:
            - 5432:5432
        volumes:
            - .docker-data/postgresql:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - 8080:8080
        depends_on:
            - database
