name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build server executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Prepare docker
        run: |
          cp target/release/bauth infra/docker/bauth

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: wadjetz/bauth

      - name: Push server docker to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./infra/docker
          file: ./infra/docker/Dockerfile
          tags: |
            ${{ steps.prepare.outputs.tag }}
            wadjetz/bauth:latest
