name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2    
      - name: Build server executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Prepare docker
        run: |
          cp -r templates infra/docker/templates
          cp target/release/bauth infra/docker

      - name: Push server docker to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./infra/docker
          image: wadjetz/bauth
          tag_with_ref: true
